### ISSUE TITLE
Missing repository description

### ISSUE THREAD

**Issue by eaedkazubi** [UnhookedMonk/I-for-Lef-Ghana#1]
Add it

**Comment by UnhookedMonk** [comment]
Is this description fine?
![Screenshot_20221206_060948](https://user-images.githubusercontent.com/68302244/205989276-e67438fe-0061-4e7e-9162-058b6fda52c7.png)

**Comment by eaedkazubi** [comment]
No, I see nothing under the About near the the green button "Code"

**Comment by UnhookedMonk** [comment]
Okay sure. I've seen it and included the description. Thank you
